version: "3"
services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    container_name: metadata-db
    volumes:
      - ./mongodb:/data/db